parser: '@typescript-eslint/parser'
env:
  es6: true
  node: true
plugins:
  - '@typescript-eslint'
extends:
  - plugin:@typescript-eslint/recommended
  - inclusive/typescript
overrides:
  - files:
      - src/**/*.test.ts
      - test/**/*.ts
    env:
      mocha: true
