version: '3.7'

services:
  app:
    build: .
    volumes:
      - ./:/app
    environment:
      REDIS_URI: redis://redis
    command: sh -c "wait-for --redis && npm test"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
